
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class SocialNetworkLogin
{

    public int ID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public Nullable<System.Guid> Userid { get; set; }

    public Nullable<int> Category { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string SocialNetworSource { get; set; }



    public virtual tblUser tblUsers { get; set; }

}

}
