
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_SocialNetworkStatus
{

    public int ID { get; set; }

    public Nullable<System.Guid> Aphid { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> CategoryID { get; set; }



    public virtual tblCategory tblCategory { get; set; }

}

}
