
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_SendLinkToMT
{

    public string ComposerName { get; set; }

    public string Title { get; set; }

    public System.Guid ChannelId { get; set; }

    public string Category { get; set; }

    public int Credits { get; set; }

    public System.Guid UserId { get; set; }

    public int ID { get; set; }

    public string Path { get; set; }

    public string TrackingNumber { get; set; }

    public Nullable<bool> LinkToPostM { get; set; }

    public string PremiumProfilePic { get; set; }

    public Nullable<bool> MessageStatus { get; set; }

    public Nullable<System.Guid> ByterUsrId { get; set; }

    public Nullable<bool> IsDelete { get; set; }

}

}
