
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_PlayList
{

    public int ID { get; set; }

    public System.Guid UserID { get; set; }

    public string PlaylistName { get; set; }

    public string FileName { get; set; }

    public string TrackingID { get; set; }

    public string Composer { get; set; }

    public int CatId { get; set; }

}

}
