
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_Messages
{

    public int id { get; set; }

    public string emailid_sender { get; set; }

    public string emailid_receiver { get; set; }

    public string message_subject { get; set; }

    public string message_body { get; set; }

    public Nullable<bool> message_status { get; set; }

    public string sender_name { get; set; }

    public string receiver_name { get; set; }

    public Nullable<System.DateTime> sending_date { get; set; }

    public Nullable<bool> Is_Read { get; set; }

}

}
