
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblAdmin
{

    public int ID { get; set; }

    public Nullable<System.Guid> AdminID { get; set; }

    public string Password { get; set; }

    public string AdminName { get; set; }

    public Nullable<bool> IsFree { get; set; }

    public Nullable<System.Guid> GroupId { get; set; }

}

}
