
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblAd
{

    public System.Guid AdID { get; set; }

    public Nullable<System.Guid> UserID { get; set; }

    public string Title { get; set; }

    public string AdInformation { get; set; }

    public Nullable<System.DateTime> AdCycleFromDate { get; set; }

    public Nullable<System.DateTime> AdCycleToDate { get; set; }

    public Nullable<int> AdTypeID { get; set; }

    public string AdVideo { get; set; }

    public string AdHyperLinkUrl { get; set; }

    public Nullable<decimal> PriceToDisplay { get; set; }

    public Nullable<int> CreditsID { get; set; }

    public Nullable<System.Guid> SurveyID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public string CompanyLogo { get; set; }

    public string AdPicture { get; set; }

    public string TrackingNo { get; set; }

    public Nullable<bool> IsActive { get; set; }



    public virtual tblMasterAdsType tblMasterAdsType { get; set; }

    public virtual tblMasterCredit tblMasterCredit { get; set; }

    public virtual tblSurveyQuestion tblSurveyQuestion { get; set; }

}

}
