
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblByteExternalSource
{

    public tblByteExternalSource()
    {

        this.tblByteExternalSourceClone = new HashSet<tblByteExternalSourceClone>();

    }


    public int ByteExternalSourceId { get; set; }

    public string ByteExternalSource { get; set; }

    public Nullable<int> ByteTypeId { get; set; }

    public string ByteExternalSourceIcon { get; set; }



    public virtual tblByteType tblByteType { get; set; }

    public virtual ICollection<tblByteExternalSourceClone> tblByteExternalSourceClone { get; set; }

}

}
