
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblByteType
{

    public tblByteType()
    {

        this.tblByteExternalSource = new HashSet<tblByteExternalSource>();

        this.tblByteSubType = new HashSet<tblByteSubType>();

    }


    public int ByteTypeId { get; set; }

    public string ByteType { get; set; }



    public virtual ICollection<tblByteExternalSource> tblByteExternalSource { get; set; }

    public virtual ICollection<tblByteSubType> tblByteSubType { get; set; }

}

}
