
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblBasicGenerateClone
{

    public int id { get; set; }

    public Nullable<System.Guid> UserID { get; set; }

    public System.Guid CloneID { get; set; }

    public string Title { get; set; }

    public string Tags { get; set; }

    public string ArtistName { get; set; }

    public string AlbumTitle { get; set; }

    public string UploadFileAudioPath { get; set; }

    public string MatrixImagePath { get; set; }

    public string Composer { get; set; }

    public string Publisher { get; set; }

    public string Producer { get; set; }

    public string SelectIntFile { get; set; }

    public string InterruptionStyle { get; set; }

    public string AvailableForDownload { get; set; }

    public string ExplicitContent { get; set; }

    public string UploadFileImagePath { get; set; }

    public string UploadFilePDFPath { get; set; }

    public string PagePercentage { get; set; }

    public string WatermarkMatrixImagePath { get; set; }

    public string WatermarkMatrixImageText { get; set; }

    public string VideoCategory { get; set; }

    public string TrackingNumber { get; set; }

    public Nullable<int> CatID { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public System.DateTime ModifyDate { get; set; }

    public bool IsActive { get; set; }

    public string VideoPath { get; set; }

    public string RarPath { get; set; }

    public string TotalLength { get; set; }

    public string UploadFileAudio2Path { get; set; }

}

}
