
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblChannelPage
{

    public System.Guid ChannelID { get; set; }

    public Nullable<System.Guid> UserID { get; set; }

    public string ChannelImagePath { get; set; }

    public string ChannelBiography { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public string UserName { get; set; }

}

}
