
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblDataStoragePlan
{

    public int ID { get; set; }

    public Nullable<System.Guid> UserID { get; set; }

    public string StoragePlan { get; set; }

    public string UsedSpace { get; set; }

    public string FreeSpace { get; set; }

    public Nullable<int> AccountTypeId { get; set; }

    public Nullable<System.DateTime> ExpireDate { get; set; }

}

}
