
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblInterruptedBasicAudioFile
{

    public int ID { get; set; }

    public System.Guid CloneID { get; set; }

    public string SongName { get; set; }

    public byte[] InterruptedByte { get; set; }

    public string Type { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
