
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblLoginTokens
{

    public System.Guid UserId { get; set; }

    public System.Guid TokenId { get; set; }

    public System.DateTime ExpirationDate { get; set; }

    public int AccountTypeId { get; set; }



    public virtual tblLoginTokens tblLoginTokens1 { get; set; }

    public virtual tblLoginTokens tblLoginTokens2 { get; set; }

    public virtual tblMasterAccountType tblMasterAccountType { get; set; }

    public virtual tblUser tblUsers { get; set; }

}

}
