
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblMasterAccountType
{

    public tblMasterAccountType()
    {

        this.tblMerchantAccounts = new HashSet<tblMerchantAccount>();

        this.tblAphidTiseAccounts = new HashSet<tblAphidTiseAccount>();

        this.tblPremiumAccounts = new HashSet<tblPremiumAccount>();

        this.tblByterAccounts = new HashSet<tblByterAccount>();

        this.tblLoginTokens = new HashSet<tblLoginTokens>();

    }


    public int AccountTypeID { get; set; }

    public string AccountTypeName { get; set; }



    public virtual ICollection<tblMerchantAccount> tblMerchantAccounts { get; set; }

    public virtual ICollection<tblAphidTiseAccount> tblAphidTiseAccounts { get; set; }

    public virtual ICollection<tblPremiumAccount> tblPremiumAccounts { get; set; }

    public virtual ICollection<tblByterAccount> tblByterAccounts { get; set; }

    public virtual ICollection<tblLoginTokens> tblLoginTokens { get; set; }

}

}
