
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblMerchantAccount
{

    public System.Guid MerchantUserID { get; set; }

    public byte[] CompanyLogo { get; set; }

    public string CompanyName { get; set; }

    public string Informations { get; set; }

    public string Websites { get; set; }

    public string EmailAddress { get; set; }

    public string Phone { get; set; }

    public string ProductServices { get; set; }

    public Nullable<System.Guid> AddressID { get; set; }

    public Nullable<System.Guid> SecurityQuestionID { get; set; }

    public Nullable<int> AccountTypeID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

    public Nullable<bool> IsDelete { get; set; }



    public virtual tblMasterAccountType tblMasterAccountType { get; set; }

    public virtual tblPersonAddress tblPersonAddress { get; set; }

    public virtual tblSecurityQuestion tblSecurityQuestion { get; set; }

}

}
