
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblPersonAddress
{

    public tblPersonAddress()
    {

        this.tblMerchantAccounts = new HashSet<tblMerchantAccount>();

        this.tblAphidlabAccounts = new HashSet<tblAphidlabAccount>();

        this.tblAphidTiseAccounts = new HashSet<tblAphidTiseAccount>();

        this.tblPremiumAccounts = new HashSet<tblPremiumAccount>();

        this.tblByterAccounts = new HashSet<tblByterAccount>();

    }


    public System.Guid AddressID { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string PostalCode { get; set; }



    public virtual ICollection<tblMerchantAccount> tblMerchantAccounts { get; set; }

    public virtual ICollection<tblAphidlabAccount> tblAphidlabAccounts { get; set; }

    public virtual ICollection<tblAphidTiseAccount> tblAphidTiseAccounts { get; set; }

    public virtual ICollection<tblPremiumAccount> tblPremiumAccounts { get; set; }

    public virtual ICollection<tblByterAccount> tblByterAccounts { get; set; }

}

}
