
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblPremiumCodes
{

    public string PremiumCode { get; set; }

    public bool AlreadyRedeemed { get; set; }

    public System.DateTime ExpirationDate { get; set; }

    public int PremiumCodeId { get; set; }

}

}
