
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblSurveyQuestion
{

    public tblSurveyQuestion()
    {

        this.tblAds = new HashSet<tblAd>();

    }


    public System.Guid SurveyID { get; set; }

    public string Question { get; set; }

    public string Option1 { get; set; }

    public string Option2 { get; set; }

    public string Option3 { get; set; }

    public string Option4 { get; set; }

    public string Option5 { get; set; }

    public string Option6 { get; set; }

    public string Option7 { get; set; }

    public string Option8 { get; set; }



    public virtual ICollection<tblAd> tblAds { get; set; }

}

}
