
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserActivation
{

    public int ID { get; set; }

    public Nullable<System.Guid> UserId { get; set; }

    public Nullable<System.Guid> TokenId { get; set; }

    public string UserName { get; set; }

    public Nullable<bool> Status { get; set; }

}

}
