
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblUser
{

    public tblUser()
    {

        this.tblAudioInterruptions = new HashSet<tblAudioInterruption>();

        this.tblVideoInterruptions = new HashSet<tblVideoInterruption>();

        this.tblWaterMarkUpInterruptions = new HashSet<tblWaterMarkUpInterruption>();

        this.tblLoginTokens = new HashSet<tblLoginTokens>();

        this.SocialNetworkLogin = new HashSet<SocialNetworkLogin>();

    }


    public System.Guid UserId { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public Nullable<bool> UserStatus { get; set; }

    public Nullable<int> AccountTypeID { get; set; }

    public string EmailAddress { get; set; }

    public string RecoveryEmail { get; set; }

    public Nullable<int> PictureServerId { get; set; }

    public string PicturePath { get; set; }

    public string StripeCustomerID { get; set; }



    public virtual ICollection<tblAudioInterruption> tblAudioInterruptions { get; set; }

    public virtual ICollection<tblVideoInterruption> tblVideoInterruptions { get; set; }

    public virtual ICollection<tblWaterMarkUpInterruption> tblWaterMarkUpInterruptions { get; set; }

    public virtual ICollection<tblLoginTokens> tblLoginTokens { get; set; }

    public virtual tblUser tblUsers1 { get; set; }

    public virtual tblUser tblUsers2 { get; set; }

    public virtual ICollection<SocialNetworkLogin> SocialNetworkLogin { get; set; }

}

}
