
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblWaterMarkUpInterruption
{

    public tblWaterMarkUpInterruption()
    {

        this.tblPremiumAccounts = new HashSet<tblPremiumAccount>();

    }


    public int ID { get; set; }

    public Nullable<System.Guid> UserId { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string WatermarkImageName { get; set; }

    public string ImageInterruption { get; set; }



    public virtual tblUser tblUser { get; set; }

    public virtual ICollection<tblPremiumAccount> tblPremiumAccounts { get; set; }

}

}
