
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AphidTise.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingBatch
{

    public int BatchId { get; set; }

    public string BatchName { get; set; }

    public string BatchDescription { get; set; }

    public Nullable<System.DateTime> BatchStartDate { get; set; }

    public string BatchTimings { get; set; }

    public Nullable<int> BatchDuration { get; set; }

    public string BatchLanguage { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

}

}
